In [75]:
import pandas as pd
from pandas import read_csv
import numpy as np

from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, mean_absolute_error

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split

df = read_csv("./database/data3.csv", delim_whitespace=False, header=None)

df = df.iloc[1:]

feature_names = ['fl','fw','mt','pl','pw','sh','sl','sw','freq','s11','gain']

df.columns = feature_names

df = df.apply(pd.to_numeric)

x = df[['pl', 'pw', 'sh']]
y = df[['freq', 's11', 'gain']]

# print(x.head())
# print(y.head())

In [87]:
import random

# poly = PolynomialFeatures(degree=1)
# temp = poly.fit_transform(x)
# x_poly = pd.DataFrame(data=temp)
# x = x_poly

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = random.randint(20, 999))

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(x_train)

X_train_scaled = scaler.transform(x_train)
X_test_scaled = scaler.transform(x_test)

lr_model = linear_model.LinearRegression()
lr_model.fit(X_train_scaled, y_train)

y_pred = lr_model.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print('Mean squared error: ', mse)
print('Mean absolute error: ', mae)

print("\n")

predictions = lr_model.predict(X_test_scaled[:5])
print("Predicted values are:\n ", predictions)

print("\n")

print("Real values are:\n ", y_test[:5])

Mean squared error:  0.1334674931460842
Mean absolute error:  0.17203965234086283


Predicted values are:
  [[  0.84432782 -16.06286371   9.49331396]
 [  0.84862889 -17.55236567   9.85831945]
 [  0.83906545 -18.75280512   9.59743993]
 [  0.84670629 -14.74181879   9.46593969]
 [  0.84374608 -18.33678949   9.69219701]]


Real values are:
         freq        s11      gain
129  0.8452 -16.463355  9.442089
203  0.8443 -16.718563  9.720795
256  0.8461 -18.425204  9.639839
32   0.8461 -14.813197  9.482648
257  0.8461 -18.161573  9.659253
