In [1]:
import pandas as pd
from pandas import read_csv
import numpy as np

from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, mean_absolute_error

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split

df = read_csv("./database/data3.csv", delim_whitespace=False, header=None)

df = df.iloc[1:]

feature_names = ['fl','fw','mt','pl','pw','sh','sl','sw','freq','s11','gain']

df.columns = feature_names

df = df.apply(pd.to_numeric)

x = df[['pl', 'pw', 'sh']]
y = df[['freq', 's11', 'gain']]

# print(x.head())
# print(y.head())

In [2]:
import random

# poly = PolynomialFeatures(degree=1)
# temp = poly.fit_transform(x)
# x_poly = pd.DataFrame(data=temp)
# x = x_poly

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = random.randint(20, 999))

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(x_train)

X_train_scaled = scaler.transform(x_train)
X_test_scaled = scaler.transform(x_test)

lr_model = linear_model.LinearRegression()
lr_model.fit(X_train_scaled, y_train)

y_pred = lr_model.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print('Mean squared error: ', mse)
print('Mean absolute error: ', mae)
 
print("\n")

predictions = lr_model.predict(X_test_scaled[:5])
print("Predicted values are:\n ", predictions)

print("\n")

print("Real values are:\n ", y_test[:5])

Mean squared error:  0.49593499056104945
Mean absolute error:  0.3339536104451866


Predicted values are:
  [[  0.8438279  -18.20349123   9.7280296 ]
 [  0.84020173 -17.66072948   9.34818018]
 [  0.84518924 -21.07625806   9.23360223]
 [  0.84177105 -17.06447573   9.37410772]
 [  0.84002182 -15.70482818   9.76044499]]


Real values are:
         freq        s11      gain
328  0.8434 -18.801751  9.623074
136  0.8452 -16.527380  9.450983
239  0.8380 -22.945224  9.075258
52   0.8533 -13.872571  9.546651
224  0.8434 -16.610590  9.698837


In [21]:
arr = [1, 3, 2, 5, 4, 8, 11, 9, 13]

for i in range(len(arr) - 1):
    try:
        if x[i] > x[i + 1]:
            x.pop(i) 
    except:
        break

print(x)

# kim jong un sort

[1, 2, 4, 8, 9, 13]
